name: Triage
on:
  pull_request_target:
    types:
      - opened
      - edited
    branches:
      - master
    paths:
      - 'xep-*.xml'
jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils
          version: cachetag1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy trusted version of script
        run: cp tools/github_auto_triage_pr.sh /tmp
      - name: Setup PR branch locally
        run: gh pr checkout ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      - run: bash /tmp/github_auto_triage_pr.sh ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
